alter table account drop foreign key fk_account_user;
alter table bank drop foreign key fk_bank_user;
alter table banktransfer drop foreign key fk_banktransfert_bank;
alter table banktransfer drop foreign key fk_banktransfert_movement;
alter table credit drop foreign key fk_credit_movement;
alter table movement drop foreign key fk_movement_account;
alter table transfer drop foreign key fk_transfer_user;
alter table transfer drop foreign key fk_transfer_movement;
alter table user_buddies drop foreign key fk_buddybuddyid_userid;
alter table user_buddies drop foreign key fk_buddyuserid_userid;
drop table if exists account;
drop table if exists bank;
drop table if exists banktransfer;
drop table if exists credit;
drop table if exists hibernate_sequence;
drop table if exists transfer;
drop table if exists movement;
drop table if exists user_buddies;
drop table if exists user;
